OpenPLC is a microcontroller based small scale PLC, It uses atmega16 as controller. 

It is programmed using free open source software LDmicro.

A PLC generally has a set of input and output ports to with the external
peripherals are connected, which are to be electrically controlled by the PLC.Looking into the flow of working of the PLC, the processor tries to make decisions in accordance to the program, generally written by the user using some logic used to program these units.

The objective is to create an Open Source PLC, which has the capa-
bilities of the industrial PLC, but the catch here is, it’s much cheaper and simpler to work with. It incorporates a development board, that works on AVR’s ATmega16A IC, giving upto 40 pins, most of which can be used and programmed as the Input-Output pins as it’s done on a PLC. Moreover, the logic used here is Ladder Logic which is one of the easiest and also, robust in terms of its efficiency. Main point here is, this device is a standalone device, which can work without the host system being there, just being powered by a source. HEX files to be generated according to the controller are generated by a software called LDMicro, freely available for Windows and Linux users alike.


